### ISSUE TITLE
Store errors at baobab state.

### ISSUE THREAD

**Issue by ir4y** [Brogency/react-form-tools#3]
For some application we are needed access to errors from external components via direct baobab access, or cursor access.
For the oposite the currebt aproach with enternal state is a good perfomance tip.
Maybe we can provide the both, and allow to select behavior via props.

For example if we pass `errorCursor` props to Form component it will use this cursor to store errors data.
If not, the internal state will be used.

**Comment by ruscoder** [comment]
Implemented in v2.0.0
