### ISSUE TITLE
Input: problem with onBlur

### ISSUE THREAD

**Issue by ruscoder** [Brogency/react-form-tools#6]
When user blurs from input, `this.state.value` is applied to cursor.
If `event.target.value` was changed from outer source, `this.state.value` overrides new value.

**Comment by ir4y** [comment]
Actually, it's works worse. I have validation issues and strange text disappearing from an input after this update.

**Comment by ruscoder** [comment]
Fixed in 1.0.14

**Comment by ruscoder** [comment]
I have found same problem in v2.0.0. I will fix this issue in both versions.

**Comment by ir4y** [comment]
I think we need to add regression tests. I have created task for it #9
